// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvC__S4iv_iH54FmqdrVONis7lc3OATFQ',
    appId: '1:895892844041:web:a75287118d85996c4552d8',
    messagingSenderId: '895892844041',
    projectId: 'ae-prueba',
    authDomain: 'ae-prueba.firebaseapp.com',
    databaseURL: 'https://ae-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'ae-prueba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBef5wfsTk7hPE80xzjMhWvGJwz1VhgD5I',
    appId: '1:895892844041:android:065e371478df64094552d8',
    messagingSenderId: '895892844041',
    projectId: 'ae-prueba',
    databaseURL: 'https://ae-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'ae-prueba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdqi_GccgW6Q_8Fdh5x9vsEyhZ8ee15-s',
    appId: '1:895892844041:ios:ed61caf3180b22634552d8',
    messagingSenderId: '895892844041',
    projectId: 'ae-prueba',
    databaseURL: 'https://ae-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'ae-prueba.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdqi_GccgW6Q_8Fdh5x9vsEyhZ8ee15-s',
    appId: '1:895892844041:ios:ed61caf3180b22634552d8',
    messagingSenderId: '895892844041',
    projectId: 'ae-prueba',
    databaseURL: 'https://ae-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'ae-prueba.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvC__S4iv_iH54FmqdrVONis7lc3OATFQ',
    appId: '1:895892844041:web:c2d5220bc0650eac4552d8',
    messagingSenderId: '895892844041',
    projectId: 'ae-prueba',
    authDomain: 'ae-prueba.firebaseapp.com',
    databaseURL: 'https://ae-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'ae-prueba.firebasestorage.app',
  );

}